services:
  - type: web
    name: unisphere
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install dj-database-url
      python manage.py collectstatic --no-input
      python manage.py migrate
      echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@example.com', 'admin123') if not User.objects.filter(username='admin').exists() else None" | python manage.py shell
    startCommand: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: unisphere-db
          property: connectionString
      - key: EMAIL_HOST_USER
        value: shyinenuv@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: izjf qawk muqb rymg
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: admin123
      - key: REDIS_URL
        fromService:
          type: redis
          name: unisphere-redis
          property: connectionString
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
    plan: free

  - type: redis
    name: unisphere-redis
    ipAllowList: []
    plan: free

  - type: postgres
    name: unisphere-db
    plan: free 