services:
  - type: web
    name: unisphere
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install dj-database-url
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_HOST_USER
        value: shyinenuv@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: izjf qawk muqb rymg
    plan: free

  - type: redis
    name: unisphere-redis
    plan: free

  - type: postgres
    name: unisphere-db
    plan: free 