# Generated by Django 5.0.2 on 2025-04-19 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_notification_post_notification_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="year",
            field=models.IntegerField(
                help_text="Enter a value between 1 and 5",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="College year must be at least 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, message="College year cannot be more than 5"
                    ),
                ],
                verbose_name="College Year",
            ),
        ),
    ]
