# Generated by Django 5.0.2 on 2025-04-19 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_post_video_alter_profile_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "mov", "avi", "mkv"]
                    )
                ],
            ),
        ),
    ]
