# Generated by Django 5.0.2 on 2025-04-29 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_emailverification_remove_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(blank=True, help_text='Enter a value between 1 and 5', null=True, validators=[django.core.validators.MinValueValidator(1, message='College year must be at least 1'), django.core.validators.MaxValueValidator(5, message='College year cannot be more than 5')], verbose_name='College Year'),
        ),
    ]
