# Generated by Django 5.0.2 on 2025-04-29 15:59

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_alter_profile_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('R', 'In a Relationship'), ('C', "It's complicated")], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default=1, help_text='Enter a value between 1 and 5', validators=[django.core.validators.MinValueValidator(1, message='College year must be at least 1'), django.core.validators.MaxValueValidator(5, message='College year cannot be more than 5')], verbose_name='College Year'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['timestamp'], name='chat_messag_timesta_6494d7_idx'),
        ),
    ]
